version: "3"
services:
  redis:
    image: 'redis'
    container_name: cache

  mongo:
    container_name: mongo
    build: ./dump
    image: 'mongo'
    
  no_sql:
    container_name: no_sql
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - "mongo"
      - "redis"
